export const careers = [
  "Ingeniería Agrícola",
  "Ingeniería Civil",
  "Ingeniería Ambiental Y De Recursos Naturales",
  "Comunicación Social",
  "Ingeniería Geográfica Y Ambiental",
  "Ingenieria Sanitaria Y Ambiental",
  "Ingeniería De Mecánica De Fluidos",
  "Ingeniería Mecánica De Fluidos",
  "Ingeniería Sanitaria",
  "Topografía",
  "Ingeniería Topográfica Y Agrimensura",
  "Ingenieria Industrial",
  "Ingeniería Forestal",
  "Ingenieria Civil",
  "Ingenieria De Materiales",
  "Administración De Empresas",
  "Contabilidad",
  "Ingeniería De Minas",
  "Ingeniería Industrial",
  "Ingenieria Industrial Y De Sistemas",
  "Ingeniería Ambiental",
  "Ingenieria Mecanica",
  "Ingenieria De Sistemas",
  "Ingeniero De Minas",
  "Ingenieria Metalurgica",
  "Ingenieria Geologica",
  "Ingenieria Electrica",
  "Ingeniero Industrial Y De Sistemas",
  "Ingenieria Ambiental",
  "Ingenieria De Minas",
  "Arquitectura",
  "Administrador De Empresas",
  "Tecnico",
  "Antropologia",
  "Ingenieria Petrolera",
  "Ingenieria Mecanica Y Electrica",
  "Ingenieria Electrica Y Electronica",
  "Ingenieria Mecanica Electrica",
  "Administrador",
  "Arqueóloga",
];

export const locations = [
  { city: "Lima", country: "Peru" },
  { city: "Arequipa", country: "Peru" },
  { city: "Cusco", country: "Peru" },
  { city: "Trujillo", country: "Peru" },
  { city: "Piura", country: "Peru" },
  { city: "Chiclayo", country: "Peru" },
  { city: "Iquitos", country: "Peru" },
  { city: "Huancayo", country: "Peru" },
  { city: "Tacna", country: "Peru" },
  { city: "Chimbote", country: "Peru" },
  { city: "Pucallpa", country: "Peru" },
  { city: "Juliaca", country: "Peru" },
  { city: "Ayacucho", country: "Peru" },
  { city: "Huaraz", country: "Peru" },
  { city: "Chachapoyas", country: "Peru" },
  { city: "Tumbes", country: "Peru" },
  { city: "Ica", country: "Peru" },
  { city: "Cajamarca", country: "Peru" },
  { city: "Puno", country: "Peru" },
  { city: "Moquegua", country: "Peru" },
  { city: "Tarapoto", country: "Peru" },
  { city: "Puerto Maldonado", country: "Peru" },
  { city: "Moyobamba", country: "Peru" },
  { city: "Talara", country: "Peru" },
  { city: "Andahuaylas", country: "Peru" },
  { city: "Cerro de Pasco", country: "Peru" },
  { city: "Huaral", country: "Peru" },
  { city: "Abancay", country: "Peru" },
  { city: "Yurimaguas", country: "Peru" },
  { city: "Tingo María", country: "Peru" },
];
