export { ButtonContainerLg } from 'pages/Account/ButtonContainerLg'
export { Onboarding } from 'pages/Account/Onboarding'
export { AppContext, AppContextProvider } from 'pages/Account/OnboardingContext'
export { Payment } from 'pages/Account/Payment'
export { Step1 } from 'pages/Account/steps/Step1'
export { Step2 } from 'pages/Account/steps/Step2'
export { Step3 } from 'pages/Account/steps/Step3'
export { Step4 } from 'pages/Account/steps/Step4'
export { Step6 } from 'pages/Account/steps/Step6'
export { AuthLayout } from 'pages/Auth/AuthLayout'
export { ForgotPass } from 'pages/Auth/ForgotPass'
export { LoginBack } from 'pages/Auth/Login.back'
export { Login } from 'pages/Auth/Login'
export { RegisterBack } from 'pages/Auth/Register.back'
export { Register } from 'pages/Auth/Register'
export { Companies } from 'pages/Community/Companies/Companies'
export { default as Media } from 'pages/Community/Media'
export { TalentDetail } from 'pages/Community/Talents/TalentDetail'
export { Talents } from 'pages/Community/Talents/Talents'
export { AdminDash } from 'pages/Dashboard/Admin/AdminDash'
export { CompanyDash } from 'pages/Dashboard/Company/CompanyDash'
export { MarketProfessionals } from 'pages/Dashboard/Company/MarketProfessionals'
export { Dashboard } from 'pages/Dashboard/Dashboard'
export { DashboardLayout } from 'pages/Dashboard/DashboardLayout'
export { DashProfessionalOffers } from 'pages/Dashboard/Professional/Offers'
export { ProfessionalDash } from 'pages/Dashboard/Professional/ProfessionalDash'
export { Error404 } from 'pages/Errors/Error404'
export { default as HomeEmpresa } from 'pages/HomeEmpresa'
export { default as About } from 'pages/Info/About'
export { default as Contact } from 'pages/Info/Contact'
export { default as InfoProfessionals } from 'pages/Info/InfoProfessionals'
export { default as News } from 'pages/Info/News'
export { OfferDetail } from 'pages/Info/OfferDetail'
export { default as Offers } from 'pages/Info/Offers'
export { default as Pricing } from 'pages/Info/pricing/Pricing'
export { PricingEmpresa } from 'pages/Info/pricing/PricingEmpresa'
export { PricingProfesional } from 'pages/Info/pricing/PricingProfesional'
export { Into } from 'pages/Into'
export { Landing } from 'pages/Landing'
export { default as UserForm } from 'pages/UserForm'
export { default as Footer } from 'pages/footer/Footer'
